version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./www:/var/www
      - ./letsencrypt:/etc/letsencrypt
