version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # Añade mapeo para HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www  # Ruta de montaje para servir el contenido de "www"
      - ./letsencrypt:/etc/letsencrypt  # Mapeo para los certificados SSL
    networks:
      - domain-net
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - domain-net

networks:
  domain-net:
    driver: bridge
